server:
    port: 8081
    
eureka: 
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: stuservice
  datasource:
    url: jdbc:mysql://localhost:3306/testzh
    username: root
    password: sheng
    driverClassName: com.mysql.jdbc.Driver 
        
